/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ashan
 */
public class AViewConsecutiveSessionRoomTable extends javax.swing.JFrame {
    
    private Connection connection;
    private Statement statement;
    private PreparedStatement preparedStmt; 

    /**
     * Creates new form AViewConsecutiveSessionRoomTable
     */
    public AViewConsecutiveSessionRoomTable() {
        initComponents();
        dbconnect();
        show_ConsecSessionRoomDetails();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public ArrayList<ARoomConsecSessionModel> roomConsecSessionList() {
        
        ArrayList<ARoomConsecSessionModel> roomConsecSessionList = new ArrayList<>();
        try {
            String query = "SELECT * FROM consecutiverooms";
            statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(query);
            
            ARoomConsecSessionModel consecsessionroommodel ;

            while(rs.next()){
                consecsessionroommodel = new ARoomConsecSessionModel (rs.getInt("consecroom_id"), rs.getString("consecroom_name"), rs.getString("sessionid1"), rs.getString("sessionid2"), rs.getString("SubCode1"), rs.getString("SubCode2"), rs.getString("SubName1"), rs.getString("SubName2"), rs.getString("Tag1"), rs.getString("Tag2"), rs.getString("Buildings"), rs.getString("rooms"));
                roomConsecSessionList.add(consecsessionroommodel);            
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex + "Exception occured in RoomList method");
            Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, ex);         
        }
        return roomConsecSessionList;            
    }
    
    public void show_ConsecSessionRoomDetails(){
        
        ArrayList<ARoomConsecSessionModel> roomConsecSessionList = roomConsecSessionList();
        DefaultTableModel tableModel = (DefaultTableModel) onlyConSessionRooms_table.getModel();
        
        Object[] row = new Object[14];
        for (int i = 0; i < roomConsecSessionList.size(); i++) {
            
            row[0] = roomConsecSessionList.get(i).getId();
            row[1] = roomConsecSessionList.get(i).getConsecSession_name();
            row[2] = roomConsecSessionList.get(i).getSessionidOne();
            row[3] = roomConsecSessionList.get(i).getSessionidTwo();
            row[4] = roomConsecSessionList.get(i).getSubject_codeOne();
            row[5] = roomConsecSessionList.get(i).getSubject_codeTwo();
            row[6] = roomConsecSessionList.get(i).getSubject_nameOne();
            row[7] = roomConsecSessionList.get(i).getSubject_nameTwo();
            row[8] = roomConsecSessionList.get(i).getConsecSession_tagOne();
            row[9] = roomConsecSessionList.get(i).getConsecSession_tagTwo();
            row[10] = roomConsecSessionList.get(i).getConsecSessionBuilding();
            row[11] = roomConsecSessionList.get(i).getConsecSessionRoom();
            
            tableModel.addRow(row);                       
        } 
    }    
    
    private void dbconnect(){
        String currentDir = System.getProperty("user.dir");
        final String DRIVER = "org.apache.derby.jdbc.EmbeddedDriver";
        final String JDBC_URL = "jdbc:derby:"+currentDir+"\\TTMS";
        
        try {
            Class.forName(DRIVER);
            connection = DriverManager.getConnection(JDBC_URL);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }  
        
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewConSessionRoomsTable_TopBar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        searchTextFieldConSessionRoomsTable = new javax.swing.JTextField();
        btn_searchviewConSessionRoomsTable = new javax.swing.JButton();
        btn_refreshviewConSessionRoomsTable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        onlyConSessionRooms_table = new javax.swing.JTable();
        viewConSessionRoomsTable_exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));

        viewConSessionRoomsTable_TopBar.setBackground(new java.awt.Color(20, 181, 117));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONSECUTIVE SESSION ROOMS TABLE");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn.png"))); // NOI18N
        jButton3.setText("LOGOUT");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn hover.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewConSessionRoomsTable_TopBarLayout = new javax.swing.GroupLayout(viewConSessionRoomsTable_TopBar);
        viewConSessionRoomsTable_TopBar.setLayout(viewConSessionRoomsTable_TopBarLayout);
        viewConSessionRoomsTable_TopBarLayout.setHorizontalGroup(
            viewConSessionRoomsTable_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewConSessionRoomsTable_TopBarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        viewConSessionRoomsTable_TopBarLayout.setVerticalGroup(
            viewConSessionRoomsTable_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewConSessionRoomsTable_TopBarLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(viewConSessionRoomsTable_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        searchTextFieldConSessionRoomsTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchTextFieldConSessionRoomsTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchTextFieldConSessionRoomsTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextFieldConSessionRoomsTableKeyReleased(evt);
            }
        });

        btn_searchviewConSessionRoomsTable.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btn_searchviewConSessionRoomsTable.setForeground(new java.awt.Color(255, 255, 255));
        btn_searchviewConSessionRoomsTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn.png"))); // NOI18N
        btn_searchviewConSessionRoomsTable.setText("Search");
        btn_searchviewConSessionRoomsTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_searchviewConSessionRoomsTable.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn hover.png"))); // NOI18N
        btn_searchviewConSessionRoomsTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchviewConSessionRoomsTableActionPerformed(evt);
            }
        });

        btn_refreshviewConSessionRoomsTable.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btn_refreshviewConSessionRoomsTable.setForeground(new java.awt.Color(255, 255, 255));
        btn_refreshviewConSessionRoomsTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn.png"))); // NOI18N
        btn_refreshviewConSessionRoomsTable.setText("Refresh");
        btn_refreshviewConSessionRoomsTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_refreshviewConSessionRoomsTable.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn hover.png"))); // NOI18N
        btn_refreshviewConSessionRoomsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_refreshviewConSessionRoomsTableMouseClicked(evt);
            }
        });
        btn_refreshviewConSessionRoomsTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshviewConSessionRoomsTableActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        onlyConSessionRooms_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID Session Name", "Session ID 1", "Session ID 2", "Subject Code 1", "Subject Code 2", "Subject  Name 1", "Subject Name 2", "Tag Name 1", "Tag Name 2", "Building", "Room"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        onlyConSessionRooms_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        onlyConSessionRooms_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(onlyConSessionRooms_table);
        if (onlyConSessionRooms_table.getColumnModel().getColumnCount() > 0) {
            onlyConSessionRooms_table.getColumnModel().getColumn(0).setMinWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(0).setPreferredWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(1).setMinWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(1).setPreferredWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(2).setMinWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(2).setPreferredWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(3).setMinWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(3).setPreferredWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(4).setMinWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(4).setPreferredWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(5).setMinWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(5).setPreferredWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(6).setMinWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(6).setPreferredWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(7).setMinWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(7).setPreferredWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(8).setMinWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(8).setPreferredWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(9).setMinWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(9).setPreferredWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(10).setMinWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(10).setPreferredWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(11).setMinWidth(170);
            onlyConSessionRooms_table.getColumnModel().getColumn(11).setPreferredWidth(170);
        }

        viewConSessionRoomsTable_exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewConSessionRoomsTable_exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewConSessionRoomsTable_exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn.png"))); // NOI18N
        viewConSessionRoomsTable_exitBtn.setText("Exit");
        viewConSessionRoomsTable_exitBtn.setToolTipText("If You click this you can close this window only");
        viewConSessionRoomsTable_exitBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewConSessionRoomsTable_exitBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn hover.png"))); // NOI18N
        viewConSessionRoomsTable_exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewConSessionRoomsTable_exitBtnMouseClicked(evt);
            }
        });
        viewConSessionRoomsTable_exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewConSessionRoomsTable_exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewConSessionRoomsTable_TopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchTextFieldConSessionRoomsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_searchviewConSessionRoomsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_refreshviewConSessionRoomsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewConSessionRoomsTable_exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(viewConSessionRoomsTable_TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_searchviewConSessionRoomsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refreshviewConSessionRoomsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTextFieldConSessionRoomsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(viewConSessionRoomsTable_exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchTextFieldConSessionRoomsTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldConSessionRoomsTableKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)onlyConSessionRooms_table.getModel();
        String search = searchTextFieldConSessionRoomsTable.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        onlyConSessionRooms_table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_searchTextFieldConSessionRoomsTableKeyReleased

    private void btn_searchviewConSessionRoomsTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchviewConSessionRoomsTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_searchviewConSessionRoomsTableActionPerformed

    private void btn_refreshviewConSessionRoomsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refreshviewConSessionRoomsTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) onlyConSessionRooms_table.getModel();
        model.setRowCount(0);
        show_ConsecSessionRoomDetails();
    }//GEN-LAST:event_btn_refreshviewConSessionRoomsTableMouseClicked

    private void btn_refreshviewConSessionRoomsTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshviewConSessionRoomsTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_refreshviewConSessionRoomsTableActionPerformed

    private void viewConSessionRoomsTable_exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewConSessionRoomsTable_exitBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewConSessionRoomsTable_exitBtnMouseClicked

    private void viewConSessionRoomsTable_exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewConSessionRoomsTable_exitBtnActionPerformed
        // TODO add your handling code here:
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_viewConSessionRoomsTable_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AViewConsecutiveSessionRoomTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AViewConsecutiveSessionRoomTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AViewConsecutiveSessionRoomTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AViewConsecutiveSessionRoomTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AViewConsecutiveSessionRoomTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_refreshviewConSessionRoomsTable;
    private javax.swing.JButton btn_searchviewConSessionRoomsTable;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable onlyConSessionRooms_table;
    private javax.swing.JTextField searchTextFieldConSessionRoomsTable;
    private javax.swing.JPanel viewConSessionRoomsTable_TopBar;
    private javax.swing.JButton viewConSessionRoomsTable_exitBtn;
    // End of variables declaration//GEN-END:variables
}
