/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagementsystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.ComboBoxEditor;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import static jdk.nashorn.internal.runtime.JSType.isNumber;

import timetablemanagementsystem.HTagsHome;
/**
 *
 * @author user
 */
public class HAddStudentGroups extends javax.swing.JFrame {
    
    private Connection connection;
    private Statement statement;
    private PreparedStatement preparedStmt;
    private String HSGroups_rowSelected;
    private String AYS, program,groupID,subGroupID;
    private int groupNo,subGroupNo;
    public String gID, subID;
     public String gID2, subID2;
    /**
     * Creates new form HAddStudentGroups
     */
    public HAddStudentGroups() {
        initComponents();
        dbconnect();
        show_SGroupDetails();
        btn_addStudentG.setBackground(new java.awt.Color(8,142,88));
    }
    public ArrayList<HStudentGroupsModel> StudentGroupsList() {
        
        ArrayList<HStudentGroupsModel> StudentGroupsList = new ArrayList<>();
        try {
            String query = "SELECT * FROM SGROUPS";
            statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(query);
            
            HStudentGroupsModel hstudentgroupsmodel ;
            
            while(rs.next()){
                hstudentgroupsmodel = new HStudentGroupsModel ( rs.getInt("ID"),rs.getString("AYS"), rs.getString("program"), rs.getInt("groupNo"),rs.getInt("subGroupNo"), rs.getString("groupID"), rs.getString("subGroupID"));
                StudentGroupsList.add(hstudentgroupsmodel);
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex + "Exception occured in TagList method");
            Logger.getLogger(HAddTags.class.getName()).log(Level.SEVERE, null, ex);         
        }
        return StudentGroupsList;
    }
    
    
     public void show_SGroupDetails(){
        ArrayList<HStudentGroupsModel>  StudentGroupsList =  StudentGroupsList();
        DefaultTableModel tableModel = (DefaultTableModel) display_sgroupstable.getModel();
        
        Object[] row = new Object[7];
        for (int i = 0; i <  StudentGroupsList.size(); i++) {
            row[0] =  StudentGroupsList.get(i).getID();
            row[1] =  StudentGroupsList.get(i).getAYS();
            row[2] =  StudentGroupsList.get(i).getprogram();
            row[3] =  StudentGroupsList.get(i).getgroupNo();
            row[4] =  StudentGroupsList.get(i).getsubGroupNo();
            row[5] =  StudentGroupsList.get(i).getgroupID();
            row[6] =  StudentGroupsList.get(i).getsubGroupID();
            
            tableModel.addRow(row);
        }
        
    }
   
     private void dbconnect(){
        final String DRIVER = "org.apache.derby.jdbc.EmbeddedDriver";
        final String JDBC_URL = "jdbc:derby:C:/Derby/TTMS;create=true";
        
        try {
            Class.forName(DRIVER);
            connection = DriverManager.getConnection(JDBC_URL);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HAddStudentGroups.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HAddStudentGroups.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }  
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background_pnl = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        btn_addStudentG = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_ManageStudentG = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addStudentG_backBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jp_addTags = new javax.swing.JPanel();
        btn_cleartagdetails = new javax.swing.JButton();
        btn_addsgroups = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        AcademicYear = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        field_groupID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        field_subgroupID = new javax.swing.JTextField();
        btn_program = new javax.swing.JComboBox<>();
        spin_groupNo = new javax.swing.JSpinner();
        spin_subgroupNo = new javax.swing.JSpinner();
        btn_generateIDs = new javax.swing.JButton();
        jp_manageSGroups = new javax.swing.JPanel();
        btn_updateSGroups = new javax.swing.JButton();
        btn_deleteSGroups = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_sgroupstable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        searchbox = new javax.swing.JTextField();
        kbacs = new javax.swing.JButton();
        btn_sarchsgroup = new javax.swing.JButton();
        btn_cleartagmanage = new javax.swing.JButton();
        AYS2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        GROUPID2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SUBGROUPID2 = new javax.swing.JTextField();
        btn_generateIDs2 = new javax.swing.JButton();
        SUBGROUPNO2 = new javax.swing.JSpinner();
        GROUPNO2 = new javax.swing.JSpinner();
        PROGRAM2 = new javax.swing.JComboBox<>();
        JPanel7 = new javax.swing.JPanel();
        addTags_TopBar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        manageTags_Topbar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background_pnl.setBackground(new java.awt.Color(247, 247, 247));

        SidePanel.setBackground(new java.awt.Color(39, 156, 109));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_addStudentG.setBackground(new java.awt.Color(39, 156, 109));
        btn_addStudentG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addStudentGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addStudentGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addStudentGMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addStudentGMousePressed(evt);
            }
        });
        btn_addStudentG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/Add_Icon.png"))); // NOI18N
        btn_addStudentG.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 37, 38));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Add Student Groups");
        btn_addStudentG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, -1));

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_addStudentG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        SidePanel.add(btn_addStudentG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 60));

        btn_ManageStudentG.setBackground(new java.awt.Color(39, 156, 109));
        btn_ManageStudentG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ManageStudentGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ManageStudentGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ManageStudentGMouseExited(evt);
            }
        });
        btn_ManageStudentG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/Manage_Icon.png"))); // NOI18N
        btn_ManageStudentG.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 37, 38));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Manage Student Groups");
        btn_ManageStudentG.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 190, -1));

        jPanel3.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_ManageStudentG.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        SidePanel.add(btn_ManageStudentG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 230, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/ABC Logo 150x150.png"))); // NOI18N
        SidePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 150, 110));

        addStudentG_backBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addStudentG_backBtn.setForeground(new java.awt.Color(255, 255, 255));
        addStudentG_backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/clear btn.png"))); // NOI18N
        addStudentG_backBtn.setText("BACK");
        addStudentG_backBtn.setToolTipText("Return to Dashboard");
        addStudentG_backBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addStudentG_backBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/clear btn hover.png"))); // NOI18N
        addStudentG_backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentG_backBtnActionPerformed(evt);
            }
        });
        SidePanel.add(addStudentG_backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 112, 31));

        jPanel6.setBackground(new java.awt.Color(247, 247, 247));
        jPanel6.setPreferredSize(new java.awt.Dimension(625, 329));
        jPanel6.setLayout(new java.awt.CardLayout());

        jp_addTags.setBackground(new java.awt.Color(247, 247, 247));

        btn_cleartagdetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cleartagdetails.setForeground(new java.awt.Color(255, 255, 255));
        btn_cleartagdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/clear btn.png"))); // NOI18N
        btn_cleartagdetails.setText("CLEAR");
        btn_cleartagdetails.setToolTipText("Clear all fields");
        btn_cleartagdetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cleartagdetails.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/clear btn hover.png"))); // NOI18N
        btn_cleartagdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleartagdetailsActionPerformed(evt);
            }
        });

        btn_addsgroups.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_addsgroups.setForeground(new java.awt.Color(255, 255, 255));
        btn_addsgroups.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/add btn.png"))); // NOI18N
        btn_addsgroups.setText("ADD");
        btn_addsgroups.setToolTipText("Add record to Database");
        btn_addsgroups.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_addsgroups.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/add btn hover.png"))); // NOI18N
        btn_addsgroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addsgroupsActionPerformed(evt);
            }
        });

        jLabel11.setText("Academic Year and Semester: ");

        AcademicYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcademicYearActionPerformed(evt);
            }
        });

        jLabel12.setText("Program");

        jLabel13.setText("Group Number:");

        jLabel14.setText("Sub Grounp Number");
        jLabel14.setToolTipText("");

        jLabel15.setText("Group ID:");

        field_groupID.setEditable(false);
        field_groupID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_groupIDActionPerformed(evt);
            }
        });

        jLabel16.setText("Sub Group ID:");

        field_subgroupID.setEditable(false);

        btn_program.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "ENG", "BM" }));

        btn_generateIDs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_generateIDs.setForeground(new java.awt.Color(255, 255, 255));
        btn_generateIDs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/add btn.png"))); // NOI18N
        btn_generateIDs.setText("Generate IDs");
        btn_generateIDs.setToolTipText("Generate IDs");
        btn_generateIDs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_generateIDs.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/add btn hover.png"))); // NOI18N
        btn_generateIDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateIDsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_addTagsLayout = new javax.swing.GroupLayout(jp_addTags);
        jp_addTags.setLayout(jp_addTagsLayout);
        jp_addTagsLayout.setHorizontalGroup(
            jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_addTagsLayout.createSequentialGroup()
                .addGroup(jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_addTagsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_addsgroups, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jp_addTagsLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(btn_program, 0, 200, Short.MAX_VALUE)
                            .addComponent(AcademicYear)
                            .addComponent(spin_groupNo)
                            .addComponent(spin_subgroupNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)))
                .addGroup(jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel15)
                        .addComponent(btn_cleartagdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(field_subgroupID)
                        .addComponent(field_groupID, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(jp_addTagsLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_generateIDs, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92))
        );
        jp_addTagsLayout.setVerticalGroup(
            jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_addTagsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AcademicYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_groupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_subgroupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_program, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spin_groupNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_generateIDs, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spin_subgroupNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addsgroups, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cleartagdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel6.add(jp_addTags, "card2");

        jp_manageSGroups.setBackground(new java.awt.Color(247, 247, 247));
        jp_manageSGroups.setMinimumSize(new java.awt.Dimension(630, 455));
        jp_manageSGroups.setPreferredSize(new java.awt.Dimension(625, 329));

        btn_updateSGroups.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_updateSGroups.setForeground(new java.awt.Color(255, 255, 255));
        btn_updateSGroups.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn.png"))); // NOI18N
        btn_updateSGroups.setText("UPDATE");
        btn_updateSGroups.setToolTipText("Update selected Record");
        btn_updateSGroups.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_updateSGroups.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn hover.png"))); // NOI18N
        btn_updateSGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateSGroupsActionPerformed(evt);
            }
        });

        btn_deleteSGroups.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_deleteSGroups.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteSGroups.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn.png"))); // NOI18N
        btn_deleteSGroups.setText("DELETE");
        btn_deleteSGroups.setToolTipText("Delete Selected record");
        btn_deleteSGroups.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_deleteSGroups.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn hover.png"))); // NOI18N
        btn_deleteSGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteSGroupsActionPerformed(evt);
            }
        });

        display_sgroupstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "AYS", "Program", "Group No", "Sub Group No", "Group ID", "Sub Group ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        display_sgroupstable.getTableHeader().setReorderingAllowed(false);
        display_sgroupstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_sgroupstableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(display_sgroupstable);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Academic Year And Semester:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Sub Group No:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Group No:");

        searchbox.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        searchbox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxKeyReleased(evt);
            }
        });

        kbacs.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        kbacs.setForeground(new java.awt.Color(255, 255, 255));
        kbacs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn.png"))); // NOI18N
        kbacs.setText("Refresh");
        kbacs.setToolTipText("Refresh Table");
        kbacs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kbacs.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn hover.png"))); // NOI18N
        kbacs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kbacsMouseClicked(evt);
            }
        });
        kbacs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbacsActionPerformed(evt);
            }
        });

        btn_sarchsgroup.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btn_sarchsgroup.setForeground(new java.awt.Color(255, 255, 255));
        btn_sarchsgroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn.png"))); // NOI18N
        btn_sarchsgroup.setText("Search");
        btn_sarchsgroup.setToolTipText("Search Details");
        btn_sarchsgroup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sarchsgroup.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn hover.png"))); // NOI18N
        btn_sarchsgroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sarchsgroupActionPerformed(evt);
            }
        });

        btn_cleartagmanage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cleartagmanage.setForeground(new java.awt.Color(255, 255, 255));
        btn_cleartagmanage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn.png"))); // NOI18N
        btn_cleartagmanage.setText("CLEAR");
        btn_cleartagmanage.setToolTipText("Clear All Fields");
        btn_cleartagmanage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cleartagmanage.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn hover.png"))); // NOI18N
        btn_cleartagmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleartagmanageActionPerformed(evt);
            }
        });

        jLabel8.setText("Group ID:");

        GROUPID2.setEditable(false);

        jLabel9.setText("Program:");

        jLabel10.setText("Sub Group ID:");

        SUBGROUPID2.setEditable(false);

        btn_generateIDs2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_generateIDs2.setForeground(new java.awt.Color(255, 255, 255));
        btn_generateIDs2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn.png"))); // NOI18N
        btn_generateIDs2.setText("Generate IDs");
        btn_generateIDs2.setToolTipText("Generate New IDs");
        btn_generateIDs2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_generateIDs2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn hover.png"))); // NOI18N
        btn_generateIDs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateIDs2ActionPerformed(evt);
            }
        });

        PROGRAM2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "ENG", "BM" }));

        javax.swing.GroupLayout jp_manageSGroupsLayout = new javax.swing.GroupLayout(jp_manageSGroups);
        jp_manageSGroups.setLayout(jp_manageSGroupsLayout);
        jp_manageSGroupsLayout.setHorizontalGroup(
            jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_manageSGroupsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_manageSGroupsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_manageSGroupsLayout.createSequentialGroup()
                        .addGap(0, 89, Short.MAX_VALUE)
                        .addGroup(jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_manageSGroupsLayout.createSequentialGroup()
                                .addGroup(jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_manageSGroupsLayout.createSequentialGroup()
                                        .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_sarchsgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(kbacs, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_manageSGroupsLayout.createSequentialGroup()
                                        .addGroup(jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AYS2)
                                            .addComponent(GROUPNO2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                            .addComponent(PROGRAM2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(50, 50, 50)
                                        .addGroup(jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel8)
                                            .addComponent(GROUPID2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                            .addComponent(jLabel10)
                                            .addComponent(SUBGROUPID2)
                                            .addComponent(jLabel18)
                                            .addComponent(SUBGROUPNO2))
                                        .addGap(15, 15, 15)))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_manageSGroupsLayout.createSequentialGroup()
                                .addComponent(btn_updateSGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btn_deleteSGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_generateIDs2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_cleartagmanage, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(123, 123, 123))))))
        );
        jp_manageSGroupsLayout.setVerticalGroup(
            jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_manageSGroupsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sarchsgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kbacs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AYS2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(SUBGROUPNO2))
                .addGap(18, 18, 18)
                .addGroup(jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GROUPID2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(PROGRAM2))
                .addGap(18, 18, 18)
                .addGroup(jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GROUPNO2)
                    .addComponent(SUBGROUPID2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_generateIDs2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jp_manageSGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_deleteSGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_updateSGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cleartagmanage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jPanel6.add(jp_manageSGroups, "card3");

        JPanel7.setBackground(new java.awt.Color(20, 181, 117));
        JPanel7.setLayout(new javax.swing.OverlayLayout(JPanel7));

        addTags_TopBar.setBackground(new java.awt.Color(20, 181, 117));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADD STUDENT GROUPS");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/clear btn.png"))); // NOI18N
        jButton3.setText("LOGOUT");
        jButton3.setToolTipText("Logout from System");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/clear btn hover.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addTags_TopBarLayout = new javax.swing.GroupLayout(addTags_TopBar);
        addTags_TopBar.setLayout(addTags_TopBarLayout);
        addTags_TopBarLayout.setHorizontalGroup(
            addTags_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTags_TopBarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        addTags_TopBarLayout.setVerticalGroup(
            addTags_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTags_TopBarLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(addTags_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        JPanel7.add(addTags_TopBar);

        manageTags_Topbar.setBackground(new java.awt.Color(20, 181, 117));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MANAGE STUDENT GROUPS");

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn.png"))); // NOI18N
        jButton5.setText("LOGOUT");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn hover.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageTags_TopbarLayout = new javax.swing.GroupLayout(manageTags_Topbar);
        manageTags_Topbar.setLayout(manageTags_TopbarLayout);
        manageTags_TopbarLayout.setHorizontalGroup(
            manageTags_TopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageTags_TopbarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        manageTags_TopbarLayout.setVerticalGroup(
            manageTags_TopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageTags_TopbarLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(manageTags_TopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        JPanel7.add(manageTags_Topbar);

        javax.swing.GroupLayout Background_pnlLayout = new javax.swing.GroupLayout(Background_pnl);
        Background_pnl.setLayout(Background_pnlLayout);
        Background_pnlLayout.setHorizontalGroup(
            Background_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_pnlLayout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Background_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Background_pnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Background_pnlLayout.setVerticalGroup(
            Background_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addGroup(Background_pnlLayout.createSequentialGroup()
                .addComponent(JPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addStudentGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addStudentGMouseClicked
        // TODO add your handling code here:
        jp_addTags.setVisible(true);
        jp_manageSGroups.setVisible(false);
        addTags_TopBar.setVisible(true);
        manageTags_Topbar.setVisible(false);
        btn_addStudentG.setBackground(new java.awt.Color(8,142,88));
        btn_ManageStudentG.setBackground(new java.awt.Color(39,156,109));
    }//GEN-LAST:event_btn_addStudentGMouseClicked

    private void btn_addStudentGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addStudentGMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addStudentGMouseEntered

    private void btn_addStudentGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addStudentGMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addStudentGMouseExited

    private void btn_addStudentGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addStudentGMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addStudentGMousePressed

    private void btn_ManageStudentGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ManageStudentGMouseClicked
        // TODO add your handling code here:
        jp_manageSGroups.setVisible(true);
        jp_addTags.setVisible(false);
        addTags_TopBar.setVisible(false);
        manageTags_Topbar.setVisible(true);
        btn_ManageStudentG.setBackground(new java.awt.Color(8,142,88));
        btn_addStudentG.setBackground(new java.awt.Color(39,156,109));
    }//GEN-LAST:event_btn_ManageStudentGMouseClicked

    private void btn_ManageStudentGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ManageStudentGMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ManageStudentGMouseEntered

    private void btn_ManageStudentGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ManageStudentGMouseExited
        // TODO add your handling code here
    }//GEN-LAST:event_btn_ManageStudentGMouseExited

    private void addStudentG_backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentG_backBtnActionPerformed
        // TODO add your handling code here:
        new HTagsHome().setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_addStudentG_backBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_addsgroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addsgroupsActionPerformed
        // TODO add your handling code here:
        this.AYS = AcademicYear.getText();
        this.program = btn_program.getSelectedItem().toString();
        this.groupNo = (int) spin_groupNo.getValue();
        this.subGroupNo = (int) spin_subgroupNo.getValue();
        this.groupID = field_groupID.getText();
        this.subGroupID = field_subgroupID.getText();
        
        if(AcademicYear.getText().equals("") ||  btn_program.getSelectedItem().equals("") || spin_groupNo.getValue().equals("0") || spin_subgroupNo.getValue().equals("0")) {
                    JOptionPane.showMessageDialog(null, "Please Fill All Fields.");
                
        } else {
            if ("" != field_subgroupID.getText()) {

                try {
                    String query_sgroupsexits = "select * from Sgroups where subgroupID='" + field_subgroupID.getText() + "' ";
                    Statement st_tag = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

                    ResultSet rs1 = st_tag.executeQuery(query_sgroupsexits);
                    if (rs1.first()) {
                        JOptionPane.showMessageDialog(null, "This student Group Already Exist");

                    } else {
                        try {
                            String query = "insert into sgroups(AYS, program, groupNo, subgroupNo, groupID, subGroupID) "
                                    + "values ( ?, ?, ? ,?, ?, ?)";

                            preparedStmt = connection.prepareStatement(query);
                            preparedStmt.setString(1, AYS);
                            preparedStmt.setString(2, program);
                            preparedStmt.setInt(3, groupNo);
                            preparedStmt.setInt(4, subGroupNo);
                            preparedStmt.setString(5, groupID);
                            preparedStmt.setString(6, subGroupID);

                            preparedStmt.execute();

                            JOptionPane.showMessageDialog(null, "Tag Added Successfully. \n Thank You!");
                            DefaultTableModel model = (DefaultTableModel) display_sgroupstable.getModel();
                            model.setRowCount(0);
                            show_SGroupDetails();


                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, "Something went wrong! Please try again.");
                            System.err.println("Got an exception!");
                            System.err.println(e.getMessage());
                            Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, e);
                        }

                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Something went wrong! Please try again.");
                    System.err.println("Got an exception!");
                    System.err.println(e.getMessage());
                    Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, e);
                }

            }

        }
        
    }//GEN-LAST:event_btn_addsgroupsActionPerformed

    private void btn_cleartagdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleartagdetailsActionPerformed
        // TODO add your handling code here:
        this.AYS = AcademicYear.getText();
        this.program = btn_program.getSelectedItem().toString();
        this.groupNo = (int) spin_groupNo.getValue();
        this.subGroupNo = (int) spin_subgroupNo.getValue();
        this.groupID = field_groupID.getText();
        this.subGroupID = field_subgroupID.getText();
        
        AcademicYear.setText("");
        btn_program.setSelectedItem("IT");
        spin_groupNo.setValue(0);
        spin_subgroupNo.setValue(0);
        field_groupID.setText("");
        field_subgroupID.setText("");
        
    }//GEN-LAST:event_btn_cleartagdetailsActionPerformed

    private void AcademicYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcademicYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcademicYearActionPerformed

    private void field_groupIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_groupIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_groupIDActionPerformed

    private void btn_generateIDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateIDsActionPerformed
        // TODO add your handling code here:
        this.AYS = AcademicYear.getText();
        this.program = btn_program.getSelectedItem().toString();
        this.groupNo = (int) spin_groupNo.getValue();
        this.subGroupNo = (int) spin_subgroupNo.getValue();
        
       
        this.gID = AYS + "." + program + "." + groupNo;     
        this.subID =AYS + "." + program+ "." + groupNo + "." + subGroupNo;
        
        field_groupID.setText(gID);
        field_subgroupID.setText(subID);
       
    }//GEN-LAST:event_btn_generateIDsActionPerformed

    private void btn_updateSGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateSGroupsActionPerformed
        // TODO add your handling code here:
     
        String updated_AYS = AYS2.getText();
        String updated_program = PROGRAM2.getSelectedItem().toString();
        String updated_groupNo = GROUPNO2.getValue().toString();
        String updated_subgroupNo = SUBGROUPNO2.getValue().toString();
        String updated_groupID = GROUPID2.getText();
        String updated_subgroupID = SUBGROUPID2.getText();
            
        if (AYS2.getText().equals("") || PROGRAM2.getSelectedItem().equals("") || GROUPNO2.getValue().equals("") || SUBGROUPNO2.getValue().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Select A Row To Update.");
        
        } else{  
            
           
             try {      
                 String query = "update SGROUPS " + "set AYS = ?, program = ?, groupNo = ?, subgroupNo = ?, groupID = ?, subGroupID = ?"
                                                    + "where ID= ?";

                preparedStmt = connection.prepareStatement(query);
                preparedStmt.setString(1, updated_AYS);
                preparedStmt.setString(2, updated_program );
                preparedStmt.setString(3, updated_groupNo);
                preparedStmt.setString(4, updated_subgroupNo);
                preparedStmt.setString(5, updated_groupID);
                preparedStmt.setString(6, updated_subgroupID );
                preparedStmt.setString(7, HSGroups_rowSelected);
               
                
                preparedStmt.execute();
                
                DefaultTableModel model = (DefaultTableModel) display_sgroupstable.getModel();
                model.setRowCount(0);
                show_SGroupDetails();
                JOptionPane.showMessageDialog(null, "Student Group details updated successfully");

                
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Something went wrong! Please try again.");
                System.err.println("Exception in Update operation : " + ex);
                System.err.println(ex.getMessage());
                Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, ex);
            }                
        }

    }//GEN-LAST:event_btn_updateSGroupsActionPerformed

    private void btn_deleteSGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteSGroupsActionPerformed
        // TODO add your handling code here:
         int opt = JOptionPane.showConfirmDialog(null, "Are you sure you want to Delete " + HSGroups_rowSelected + " - "
                + subGroupID + " details ?", "Delete", JOptionPane.YES_NO_OPTION);
        
        if (opt == 0) {
            try {                
                String query = "DELETE FROM SGROUPS WHERE ID =?";
                preparedStmt = connection.prepareStatement(query);
                preparedStmt.setString(1, HSGroups_rowSelected);                
                
                preparedStmt.execute();
                
                JOptionPane.showMessageDialog(null, "Student Group removed successfully from the Database");
                DefaultTableModel model = (DefaultTableModel) display_sgroupstable.getModel();
                model.setRowCount(0);
                show_SGroupDetails();
                
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Something went wrong! Please try again.");
                System.err.println("Exception in delete operation : " + ex);
                System.err.println(ex.getMessage());
                Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }

    }//GEN-LAST:event_btn_deleteSGroupsActionPerformed

    private void display_sgroupstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_sgroupstableMouseClicked
        // TODO add your handling code here:
        int i = display_sgroupstable.getSelectedRow();
        TableModel model = display_sgroupstable.getModel();
        AYS2.setText(model.getValueAt(i, 1).toString());
        PROGRAM2.setSelectedItem(model.getValueAt(i, 2).toString());
        GROUPNO2.setValue(model.getValueAt(i, 3));
        SUBGROUPNO2.setValue(model.getValueAt(i, 4));
        GROUPID2.setText(model.getValueAt(i, 5).toString());
        SUBGROUPID2.setText(model.getValueAt(i, 6).toString());

        HSGroups_rowSelected = model.getValueAt(i, 0).toString();
        AYS = model.getValueAt(i,1).toString();
        program = model.getValueAt(i,2).toString();
        groupNo = Integer.parseInt(model.getValueAt(i,3).toString());
        subGroupNo = Integer.parseInt(model.getValueAt(i,4).toString());
        groupID = model.getValueAt(i,5).toString();
        subGroupID = model.getValueAt(i,6).toString();
        

    }//GEN-LAST:event_display_sgroupstableMouseClicked

    private void searchboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)display_sgroupstable.getModel();
        String search = searchbox.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        display_sgroupstable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_searchboxKeyReleased

    private void kbacsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kbacsMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_kbacsMouseClicked

    private void kbacsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbacsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kbacsActionPerformed

    private void btn_sarchsgroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sarchsgroupActionPerformed
        // TODO add your handling code here:
         DefaultTableModel table_model = (DefaultTableModel) display_sgroupstable.getModel();
        String searchTxt = searchbox.getText().toString();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table_model);
        display_sgroupstable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchTxt));
    }//GEN-LAST:event_btn_sarchsgroupActionPerformed

    private void btn_cleartagmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleartagmanageActionPerformed
        // TODO add your handling code here:
        AYS2.setText("");
        PROGRAM2.setSelectedItem("IT");
        GROUPNO2.setValue(0);
        SUBGROUPNO2.setValue(0);
        GROUPID2.setText("");
        SUBGROUPID2.setText("");

    }//GEN-LAST:event_btn_cleartagmanageActionPerformed

    private void btn_generateIDs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateIDs2ActionPerformed
        // TODO add your handling code here:
        this.AYS = AYS2.getText();
        this.program = PROGRAM2.getSelectedItem().toString();
        this.groupNo = (int) GROUPNO2.getValue();
        this.subGroupNo = (int) SUBGROUPNO2.getValue();
        
       
        this.gID2 = AYS + "." + program +"." + groupNo;     
        this.subID2 =AYS + "." + program +"." + groupNo + "." + subGroupNo;
        
        GROUPID2.setText(gID2);
        SUBGROUPID2.setText(subID2);
    }//GEN-LAST:event_btn_generateIDs2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HAddStudentGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HAddStudentGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HAddStudentGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HAddStudentGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HAddStudentGroups().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AYS2;
    private javax.swing.JTextField AcademicYear;
    private javax.swing.JPanel Background_pnl;
    private javax.swing.JTextField GROUPID2;
    private javax.swing.JSpinner GROUPNO2;
    private javax.swing.JPanel JPanel7;
    private javax.swing.JComboBox<String> PROGRAM2;
    private javax.swing.JTextField SUBGROUPID2;
    private javax.swing.JSpinner SUBGROUPNO2;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JButton addStudentG_backBtn;
    private javax.swing.JPanel addTags_TopBar;
    private javax.swing.JPanel btn_ManageStudentG;
    private javax.swing.JPanel btn_addStudentG;
    private javax.swing.JButton btn_addsgroups;
    private javax.swing.JButton btn_cleartagdetails;
    private javax.swing.JButton btn_cleartagmanage;
    private javax.swing.JButton btn_deleteSGroups;
    private javax.swing.JButton btn_generateIDs;
    private javax.swing.JButton btn_generateIDs2;
    private javax.swing.JComboBox<String> btn_program;
    private javax.swing.JButton btn_sarchsgroup;
    private javax.swing.JButton btn_updateSGroups;
    private javax.swing.JTable display_sgroupstable;
    private javax.swing.JTextField field_groupID;
    private javax.swing.JTextField field_subgroupID;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp_addTags;
    private javax.swing.JPanel jp_manageSGroups;
    private javax.swing.JButton kbacs;
    private javax.swing.JPanel manageTags_Topbar;
    private javax.swing.JTextField searchbox;
    private javax.swing.JSpinner spin_groupNo;
    private javax.swing.JSpinner spin_subgroupNo;
    // End of variables declaration//GEN-END:variables
}
