/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagementsystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.ComboBoxEditor;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import static jdk.nashorn.internal.runtime.JSType.isNumber;

import timetablemanagementsystem.HTagsHome;
/**
 *
 * @author user
 */
public class HAddTags extends javax.swing.JFrame {

    private Connection connection;
    private Statement statement;
    private PreparedStatement preparedStmt;
    private String HTag_rowSelected;
    private String tag_name, related_tag;
    private String tag_code;
    
    /**
     * Creates new form HAddTags
     */
    public HAddTags() {
        initComponents();
        dbconnect();
        show_TagDetails();
        btn_addTags.setBackground(new java.awt.Color(8,142,88));
    }
    public ArrayList<HTagsModel> TagsList() {
        
        ArrayList<HTagsModel> TagsList = new ArrayList<>();
        try {
            String query = "SELECT * FROM TAGS";
            statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(query);
            
            HTagsModel htagsmodel ;
            
            while(rs.next()){
                htagsmodel = new HTagsModel (rs.getInt("ID"), rs.getString("tag_name"), rs.getString("tag_code"), rs.getString("related_tag"));
                TagsList.add(htagsmodel);
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex + "Exception occured in TagList method");
            Logger.getLogger(HAddTags.class.getName()).log(Level.SEVERE, null, ex);         
        }
        return TagsList;
    }
    
   public void show_TagDetails(){
        ArrayList<HTagsModel> TagsList = TagsList();
        DefaultTableModel tableModel = (DefaultTableModel) display_tagstable.getModel();
        
        Object[] row = new Object[4];
        for (int i = 0; i < TagsList.size(); i++) {
            row[0] = TagsList.get(i).getID();
            row[1] = TagsList.get(i).gettagName();
            row[2] = TagsList.get(i).gettagCode();
            row[3] = TagsList.get(i).getrelatedTag();
            
            tableModel.addRow(row);
        }
    }
    
     private void dbconnect(){
        String currentDir = System.getProperty("user.dir");
        final String DRIVER = "org.apache.derby.jdbc.EmbeddedDriver";
        final String JDBC_URL = "jdbc:derby:"+currentDir+"\\TTMS";
        
        try {
            Class.forName(DRIVER);
            connection = DriverManager.getConnection(JDBC_URL);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HAddTags.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HAddTags.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }  
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background_pnl = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        btn_addTags = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_ManageTags = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addTags_backBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jp_addTags = new javax.swing.JPanel();
        btn_cleartagdetails = new javax.swing.JButton();
        btn_tadd = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tagName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tagCode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        relatedTag = new javax.swing.JComboBox<>();
        jp_manageTags = new javax.swing.JPanel();
        btn_updateTags = new javax.swing.JButton();
        btn_deleteTags = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_tagstable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tagCode2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        searchbox = new javax.swing.JTextField();
        kbacs = new javax.swing.JButton();
        btn_searchTag = new javax.swing.JButton();
        btn_cleartagmanage = new javax.swing.JButton();
        tagName2 = new javax.swing.JTextField();
        relatedTag2 = new javax.swing.JComboBox<>();
        JPanel7 = new javax.swing.JPanel();
        addTags_TopBar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        manageTags_Topbar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background_pnl.setBackground(new java.awt.Color(247, 247, 247));

        SidePanel.setBackground(new java.awt.Color(39, 156, 109));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_addTags.setBackground(new java.awt.Color(39, 156, 109));
        btn_addTags.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addTagsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addTagsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addTagsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addTagsMousePressed(evt);
            }
        });
        btn_addTags.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/Add_Icon.png"))); // NOI18N
        btn_addTags.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, 37, 38));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Add Tags");
        btn_addTags.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 20, 106, -1));

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_addTags.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        SidePanel.add(btn_addTags, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 60));

        btn_ManageTags.setBackground(new java.awt.Color(39, 156, 109));
        btn_ManageTags.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ManageTagsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ManageTagsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ManageTagsMouseExited(evt);
            }
        });
        btn_ManageTags.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/Manage_Icon.png"))); // NOI18N
        btn_ManageTags.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, 37, 38));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Manage Tags");
        btn_ManageTags.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 20, 143, -1));

        jPanel3.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_ManageTags.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        SidePanel.add(btn_ManageTags, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 230, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/ABC Logo 150x150.png"))); // NOI18N
        SidePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 150, 110));

        addTags_backBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addTags_backBtn.setForeground(new java.awt.Color(255, 255, 255));
        addTags_backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/clear btn.png"))); // NOI18N
        addTags_backBtn.setText("BACK");
        addTags_backBtn.setToolTipText("Return To Dashboard");
        addTags_backBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addTags_backBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/clear btn hover.png"))); // NOI18N
        addTags_backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTags_backBtnActionPerformed(evt);
            }
        });
        SidePanel.add(addTags_backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 112, 31));

        jPanel6.setBackground(new java.awt.Color(247, 247, 247));
        jPanel6.setPreferredSize(new java.awt.Dimension(625, 329));
        jPanel6.setLayout(new java.awt.CardLayout());

        jp_addTags.setBackground(new java.awt.Color(247, 247, 247));

        btn_cleartagdetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cleartagdetails.setForeground(new java.awt.Color(255, 255, 255));
        btn_cleartagdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/clear btn.png"))); // NOI18N
        btn_cleartagdetails.setText("CLEAR");
        btn_cleartagdetails.setToolTipText("Clear All Fields");
        btn_cleartagdetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cleartagdetails.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/clear btn hover.png"))); // NOI18N
        btn_cleartagdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleartagdetailsActionPerformed(evt);
            }
        });

        btn_tadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_tadd.setForeground(new java.awt.Color(255, 255, 255));
        btn_tadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/add btn.png"))); // NOI18N
        btn_tadd.setText("ADD");
        btn_tadd.setToolTipText("Add record to Database");
        btn_tadd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tadd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/add btn hover.png"))); // NOI18N
        btn_tadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taddActionPerformed(evt);
            }
        });

        jLabel11.setText("Tag Name:");

        jLabel12.setText("tag Code:");

        jLabel13.setText("Related Tag");

        relatedTag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecture", "Tutorial", "Lab Session" }));
        relatedTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatedTagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_addTagsLayout = new javax.swing.GroupLayout(jp_addTags);
        jp_addTags.setLayout(jp_addTagsLayout);
        jp_addTagsLayout.setHorizontalGroup(
            jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_addTagsLayout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addGroup(jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_addTagsLayout.createSequentialGroup()
                        .addComponent(btn_tadd, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cleartagdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_addTagsLayout.createSequentialGroup()
                        .addGroup(jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(tagName)
                            .addComponent(tagCode)
                            .addComponent(relatedTag, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(199, 199, 199))))
        );
        jp_addTagsLayout.setVerticalGroup(
            jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_addTagsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tagName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tagCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(relatedTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(jp_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tadd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cleartagdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jPanel6.add(jp_addTags, "card2");

        jp_manageTags.setBackground(new java.awt.Color(247, 247, 247));
        jp_manageTags.setMinimumSize(new java.awt.Dimension(630, 455));
        jp_manageTags.setPreferredSize(new java.awt.Dimension(625, 329));

        btn_updateTags.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_updateTags.setForeground(new java.awt.Color(255, 255, 255));
        btn_updateTags.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn.png"))); // NOI18N
        btn_updateTags.setText("UPDATE");
        btn_updateTags.setToolTipText("Update Selected Record");
        btn_updateTags.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_updateTags.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn hover.png"))); // NOI18N
        btn_updateTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateTagsActionPerformed(evt);
            }
        });

        btn_deleteTags.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_deleteTags.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteTags.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn.png"))); // NOI18N
        btn_deleteTags.setText("DELETE");
        btn_deleteTags.setToolTipText("Delete Selected Record");
        btn_deleteTags.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_deleteTags.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn hover.png"))); // NOI18N
        btn_deleteTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteTagsActionPerformed(evt);
            }
        });

        display_tagstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tag Name", "Tag Code", "Related Tag"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        display_tagstable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        display_tagstable.getTableHeader().setReorderingAllowed(false);
        display_tagstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_tagstableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(display_tagstable);
        if (display_tagstable.getColumnModel().getColumnCount() > 0) {
            display_tagstable.getColumnModel().getColumn(0).setMinWidth(180);
            display_tagstable.getColumnModel().getColumn(1).setMinWidth(180);
            display_tagstable.getColumnModel().getColumn(2).setMinWidth(180);
            display_tagstable.getColumnModel().getColumn(3).setMinWidth(180);
        }

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Tag Name:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Tag Code:");

        tagCode2.setForeground(new java.awt.Color(51, 51, 51));
        tagCode2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tagCode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagCode2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Related Tag:");

        searchbox.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        searchbox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxKeyReleased(evt);
            }
        });

        kbacs.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        kbacs.setForeground(new java.awt.Color(255, 255, 255));
        kbacs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn.png"))); // NOI18N
        kbacs.setText("Refresh");
        kbacs.setToolTipText("Refresh Table");
        kbacs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kbacs.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn hover.png"))); // NOI18N
        kbacs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kbacsMouseClicked(evt);
            }
        });
        kbacs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbacsActionPerformed(evt);
            }
        });

        btn_searchTag.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btn_searchTag.setForeground(new java.awt.Color(255, 255, 255));
        btn_searchTag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn.png"))); // NOI18N
        btn_searchTag.setText("Search");
        btn_searchTag.setToolTipText("Search Details from Database");
        btn_searchTag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_searchTag.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/add btn hover.png"))); // NOI18N
        btn_searchTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchTagActionPerformed(evt);
            }
        });

        btn_cleartagmanage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cleartagmanage.setForeground(new java.awt.Color(255, 255, 255));
        btn_cleartagmanage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn.png"))); // NOI18N
        btn_cleartagmanage.setText("CLEAR");
        btn_cleartagmanage.setToolTipText("Clear All Fields");
        btn_cleartagmanage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cleartagmanage.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn hover.png"))); // NOI18N
        btn_cleartagmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleartagmanageActionPerformed(evt);
            }
        });

        tagName2.setEditable(false);

        relatedTag2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecture", "Tutorial", "Lab Session" }));
        relatedTag2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatedTag2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_manageTagsLayout = new javax.swing.GroupLayout(jp_manageTags);
        jp_manageTags.setLayout(jp_manageTagsLayout);
        jp_manageTagsLayout.setHorizontalGroup(
            jp_manageTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_manageTagsLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jp_manageTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_manageTagsLayout.createSequentialGroup()
                        .addGroup(jp_manageTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_manageTagsLayout.createSequentialGroup()
                                .addGroup(jp_manageTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(relatedTag2, 0, 206, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tagName2))
                                .addGap(50, 50, 50)
                                .addGroup(jp_manageTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(tagCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_manageTagsLayout.createSequentialGroup()
                                .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_searchTag, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(kbacs, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_manageTagsLayout.createSequentialGroup()
                        .addComponent(btn_updateTags, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btn_deleteTags, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cleartagmanage, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
        );
        jp_manageTagsLayout.setVerticalGroup(
            jp_manageTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_manageTagsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jp_manageTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_searchTag, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kbacs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_manageTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_manageTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tagName2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(relatedTag2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jp_manageTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_deleteTags, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_updateTags, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cleartagmanage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        jPanel6.add(jp_manageTags, "card3");

        JPanel7.setBackground(new java.awt.Color(20, 181, 117));
        JPanel7.setLayout(new javax.swing.OverlayLayout(JPanel7));

        addTags_TopBar.setBackground(new java.awt.Color(20, 181, 117));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADD TAGS");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/clear btn.png"))); // NOI18N
        jButton3.setText("LOGOUT");
        jButton3.setToolTipText("Logout from system");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/HImages/clear btn hover.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addTags_TopBarLayout = new javax.swing.GroupLayout(addTags_TopBar);
        addTags_TopBar.setLayout(addTags_TopBarLayout);
        addTags_TopBarLayout.setHorizontalGroup(
            addTags_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTags_TopBarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        addTags_TopBarLayout.setVerticalGroup(
            addTags_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTags_TopBarLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(addTags_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        JPanel7.add(addTags_TopBar);

        manageTags_Topbar.setBackground(new java.awt.Color(20, 181, 117));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MANAGE TAGS");

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn.png"))); // NOI18N
        jButton5.setText("LOGOUT");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn hover.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageTags_TopbarLayout = new javax.swing.GroupLayout(manageTags_Topbar);
        manageTags_Topbar.setLayout(manageTags_TopbarLayout);
        manageTags_TopbarLayout.setHorizontalGroup(
            manageTags_TopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageTags_TopbarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        manageTags_TopbarLayout.setVerticalGroup(
            manageTags_TopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageTags_TopbarLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(manageTags_TopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        JPanel7.add(manageTags_Topbar);

        javax.swing.GroupLayout Background_pnlLayout = new javax.swing.GroupLayout(Background_pnl);
        Background_pnl.setLayout(Background_pnlLayout);
        Background_pnlLayout.setHorizontalGroup(
            Background_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_pnlLayout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Background_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Background_pnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Background_pnlLayout.setVerticalGroup(
            Background_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Background_pnlLayout.createSequentialGroup()
                .addComponent(JPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_taddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taddActionPerformed
        // TODO add your handling code here:
        this.tag_name = tagName.getText();
        this.tag_code = tagCode.getText();
        this.related_tag = relatedTag.getSelectedItem().toString();
        
        if(tagName.getText().equals("") ||  tagCode.getText().equals("") || relatedTag.getSelectedItem().equals("") ) {
                    JOptionPane.showMessageDialog(null, "Please Fill All Fields.");
                
        } else {
            if ("" != tagName.getText()) {

                try {
                    String query_tagsexits = "select * from tags where tag_name='" + tagName.getText() + "'";
                    Statement st_tag = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

                    ResultSet rs1 = st_tag.executeQuery(query_tagsexits);
                    if (rs1.first()) {
                        JOptionPane.showMessageDialog(null, "This Tag Already Exist");

                    } else {
                        try {
                            String query = "insert into tags(tag_name, tag_code, related_tag) "
                                    + "values ( ?, ?, ? )";

                            preparedStmt = connection.prepareStatement(query);
                            preparedStmt.setString(1, tag_name);
                            preparedStmt.setString(2, tag_code);
                            preparedStmt.setString(3, related_tag);

                            preparedStmt.execute();

                            JOptionPane.showMessageDialog(null, "Tag Added Successfully. \n Thank You!");
                            DefaultTableModel model = (DefaultTableModel) display_tagstable.getModel();
                            model.setRowCount(0);
                            show_TagDetails();


                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, "Something went wrong! Please try again.");
                            System.err.println("Got an exception!");
                            System.err.println(e.getMessage());
                            Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, e);
                        }

                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Something went wrong! Please try again.");
                    System.err.println("Got an exception!");
                    System.err.println(e.getMessage());
                    Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, e);
                }

            }

        }
    }//GEN-LAST:event_btn_taddActionPerformed

    private void btn_cleartagdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleartagdetailsActionPerformed
        // TODO add your handling code here:
        tagName.setText("");
        tagCode.setText("");
        relatedTag.setSelectedItem("Lecture");
    }//GEN-LAST:event_btn_cleartagdetailsActionPerformed

    private void addTags_backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTags_backBtnActionPerformed
        // TODO add your handling code here:
        
        new HTagsHome().setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_addTags_backBtnActionPerformed

    private void btn_ManageTagsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ManageTagsMouseExited
        // TODO add your handling code here
    }//GEN-LAST:event_btn_ManageTagsMouseExited

    private void btn_ManageTagsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ManageTagsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ManageTagsMouseEntered

    private void btn_ManageTagsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ManageTagsMouseClicked
        // TODO add your handling code here:
        jp_manageTags.setVisible(true);
        jp_addTags.setVisible(false);
        addTags_TopBar.setVisible(false);
        manageTags_Topbar.setVisible(true);
        btn_ManageTags.setBackground(new java.awt.Color(8,142,88));
        btn_addTags.setBackground(new java.awt.Color(39,156,109));
    }//GEN-LAST:event_btn_ManageTagsMouseClicked

    private void btn_addTagsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addTagsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addTagsMousePressed

    private void btn_addTagsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addTagsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addTagsMouseExited

    private void btn_addTagsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addTagsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addTagsMouseEntered

    private void btn_addTagsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addTagsMouseClicked
        // TODO add your handling code here:
        jp_addTags.setVisible(true);
        jp_manageTags.setVisible(false);
        addTags_TopBar.setVisible(true);
        manageTags_Topbar.setVisible(false);
        btn_addTags.setBackground(new java.awt.Color(8,142,88));
        btn_ManageTags.setBackground(new java.awt.Color(39,156,109));
    }//GEN-LAST:event_btn_addTagsMouseClicked

    private void relatedTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatedTagActionPerformed
        // TODO add your handling code here:
        String selectedValue = relatedTag.getSelectedItem().toString();
       
        
    }//GEN-LAST:event_relatedTagActionPerformed

    private void btn_updateTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateTagsActionPerformed
        // TODO add your handling code here:
        String updated_tagName = tagName2.getText();
        String updated_tagCode = tagCode2.getText();
        String updated_relatedTag = relatedTag2.getSelectedItem().toString();
            
        if (tagName2.getText().equals("") || tagCode2.getText().equals("") || relatedTag2.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Select A Row To Update.");
        
        } else{  
            
             try {      
                 String query = "update TAGS " + "set tag_name = ?, tag_code = ?, related_tag = ?"
                                                    + "where ID= ?";

                preparedStmt = connection.prepareStatement(query);
                preparedStmt.setString(1, updated_tagName);
                preparedStmt.setString(2, updated_tagCode );
                preparedStmt.setString(3, updated_relatedTag);
                preparedStmt.setString(4, HTag_rowSelected);
               
                
                preparedStmt.execute();
                
                DefaultTableModel model = (DefaultTableModel) display_tagstable.getModel();
                model.setRowCount(0);
                show_TagDetails();
                JOptionPane.showMessageDialog(null, "Tag details updated successfully");

                
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Something went wrong! Please try again.");
                System.err.println("Exception in Update operation : " + ex);
                System.err.println(ex.getMessage());
                Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, ex);
            }                
        }
        
        
    }//GEN-LAST:event_btn_updateTagsActionPerformed

    private void btn_deleteTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteTagsActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Are you sure you want to Delete " + HTag_rowSelected + " - "
                + tag_name + " details ?", "Delete", JOptionPane.YES_NO_OPTION);
        
        if (opt == 0) {
            try {                
                String query = "DELETE FROM TAGS WHERE ID =?";
                preparedStmt = connection.prepareStatement(query);
                preparedStmt.setString(1, HTag_rowSelected);                
                
                preparedStmt.execute();
                
                JOptionPane.showMessageDialog(null, "Tag removed successfully from the Database");
                DefaultTableModel model = (DefaultTableModel) display_tagstable.getModel();
                model.setRowCount(0);
                show_TagDetails();
                
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Something went wrong! Please try again.");
                System.err.println("Exception in delete operation : " + ex);
                System.err.println(ex.getMessage());
                Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
       
    }//GEN-LAST:event_btn_deleteTagsActionPerformed

    private void display_tagstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_tagstableMouseClicked
        // TODO add your handling code here:
             int i = display_tagstable.getSelectedRow();
        TableModel model = display_tagstable.getModel();    
        tagName2.setText(model.getValueAt(i, 1).toString());
        tagCode2.setText(model.getValueAt(i, 2).toString());
        relatedTag2.setSelectedItem(model.getValueAt(i,3).toString());
        
        HTag_rowSelected = model.getValueAt(i, 0).toString();
        tag_name = model.getValueAt(i,1).toString(); 
        tag_code = model.getValueAt(i,2).toString();
        related_tag = model.getValueAt(i,3).toString();
        

    }//GEN-LAST:event_display_tagstableMouseClicked

    private void tagCode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagCode2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tagCode2ActionPerformed

    private void searchboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)display_tagstable.getModel();
        String search = searchbox.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        display_tagstable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_searchboxKeyReleased

    private void kbacsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kbacsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_kbacsMouseClicked

    private void kbacsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbacsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kbacsActionPerformed

    private void btn_searchTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchTagActionPerformed
        // TODO add your handling code here:
         DefaultTableModel table_model = (DefaultTableModel) display_tagstable.getModel();
        String searchTxt = searchbox.getText().toString();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table_model);
        display_tagstable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchTxt));
    }//GEN-LAST:event_btn_searchTagActionPerformed

    private void btn_cleartagmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleartagmanageActionPerformed
        // TODO add your handling code here:
        tagName2.setText("");
        tagCode2.setText("");
        relatedTag2.setSelectedItem("Lecture");
     
    }//GEN-LAST:event_btn_cleartagmanageActionPerformed

    private void relatedTag2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatedTag2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relatedTag2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HAddTags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HAddTags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HAddTags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HAddTags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HAddTags().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background_pnl;
    private javax.swing.JPanel JPanel7;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel addTags_TopBar;
    private javax.swing.JButton addTags_backBtn;
    private javax.swing.JPanel btn_ManageTags;
    private javax.swing.JPanel btn_addTags;
    private javax.swing.JButton btn_cleartagdetails;
    private javax.swing.JButton btn_cleartagmanage;
    private javax.swing.JButton btn_deleteTags;
    private javax.swing.JButton btn_searchTag;
    private javax.swing.JButton btn_tadd;
    private javax.swing.JButton btn_updateTags;
    private javax.swing.JTable display_tagstable;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp_addTags;
    private javax.swing.JPanel jp_manageTags;
    private javax.swing.JButton kbacs;
    private javax.swing.JPanel manageTags_Topbar;
    private javax.swing.JComboBox<String> relatedTag;
    private javax.swing.JComboBox<String> relatedTag2;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTextField tagCode;
    private javax.swing.JTextField tagCode2;
    private javax.swing.JTextField tagName;
    private javax.swing.JTextField tagName2;
    // End of variables declaration//GEN-END:variables
}
