/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author umesha
 */
public class URoomCannotBeReserved extends javax.swing.JFrame {
    
    private Connection connection;
    private Statement statement;
    private PreparedStatement preparedStmt;
    private String roomCnNot_rowSelected;  
    private String  roomname, roomday, start_time, end_time;
    private int roomcannot_id;
    /**
     * Creates new form URoomCannotBeReserved
     */
    public URoomCannotBeReserved() {
        initComponents();
        dbconnect();
        show_RoomCannotReceiveDetails();
        FillComboRooms();
        btn_addWorkingDays.setBackground(new java.awt.Color(8,142,88));
    }
    
    public ArrayList<URoomCannotModel> roomcannotList() {
        
        ArrayList<URoomCannotModel> roomcannotList = new ArrayList<>();
        try {
            String query = "SELECT * FROM rmcnnot";
            statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(query);
            
            URoomCannotModel roomcannotmodel ;

            while(rs.next()){
                roomcannotmodel = new URoomCannotModel (rs.getInt("rmcannot_id"), rs.getString("room_name"), rs.getString("day"), rs.getString("start_time"), rs.getString("end_time"));
                roomcannotList.add(roomcannotmodel);            
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex + "Exception occured in Room Cannot Received List method");
            Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, ex);         
        }
        return roomcannotList;            
    }
    
    public void show_RoomCannotReceiveDetails(){
        
        ArrayList<URoomCannotModel> roomcannotList = roomcannotList();
        DefaultTableModel tableModel = (DefaultTableModel) displayroomcannot_table.getModel();
        
        Object[] row = new Object[6];
        for (int i = 0; i < roomcannotList.size(); i++) {
            
            row[0] = roomcannotList.get(i).getId();
            row[1] = roomcannotList.get(i).getRoomName();
            row[2] = roomcannotList.get(i).getRoomday();
            row[3] = roomcannotList.get(i).getStart_time();
            row[4] = roomcannotList.get(i).getEnd_time();
            
            tableModel.addRow(row);                       
        } 
    }    
    
    private void dbconnect(){
        String currentDir = System.getProperty("user.dir");
        final String DRIVER = "org.apache.derby.jdbc.EmbeddedDriver";
        final String JDBC_URL = "jdbc:derby:"+currentDir+"\\TTMS";
        
        try {
            Class.forName(DRIVER);
            connection = DriverManager.getConnection(JDBC_URL);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }  
        
    } 
    
    private void clearFieldsAdd(){
        rmcnotSelectRoom.setSelectedItem("Select Room");
        rmcannotDay.setSelectedItem("Select Day");
        emcntStart_Timetext.setText(null);
        emcntEnd_Timetext.setText(null);
    }   
    
    private void FillComboRooms(){
        try {
            String bcomboquery = "SELECT * FROM ROOMS";
            preparedStmt = connection.prepareStatement(bcomboquery);
            ResultSet rst = preparedStmt.executeQuery();
            
            while(rst.next()){
                String roomnames = rst.getString("ROOM_NAME");
                rmcnotSelectRoom.addItem(roomnames);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background_pnl = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        btn_addWorkingDays = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_ManageWorkingDays = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addWorkingDays_backBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jp_RoomCannotbeReserved = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        rmcnotSelectRoom = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_clearworkingdays = new javax.swing.JButton();
        addRoomCannotDays = new javax.swing.JButton();
        label1 = new java.awt.Label();
        rmcannotDay = new javax.swing.JComboBox<>();
        emcntStart_Timetext = new javax.swing.JTextField();
        emcntEnd_Timetext = new javax.swing.JTextField();
        jp_manageRoomCannotbereserved = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        displayroomcannot_table = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jComboBox6 = new javax.swing.JComboBox<>();
        JPanel7 = new javax.swing.JPanel();
        addWorkingDays_TopBar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        manageWorkingDays_Topbar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background_pnl.setBackground(new java.awt.Color(247, 247, 247));

        SidePanel.setBackground(new java.awt.Color(39, 156, 109));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_addWorkingDays.setBackground(new java.awt.Color(39, 156, 109));
        btn_addWorkingDays.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addWorkingDaysMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addWorkingDaysMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addWorkingDaysMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addWorkingDaysMousePressed(evt);
            }
        });
        btn_addWorkingDays.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/Add_Icon.png"))); // NOI18N
        btn_addWorkingDays.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 37, 38));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Add Room");
        btn_addWorkingDays.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 150, -1));

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_addWorkingDays.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        SidePanel.add(btn_addWorkingDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 60));

        btn_ManageWorkingDays.setBackground(new java.awt.Color(39, 156, 109));
        btn_ManageWorkingDays.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ManageWorkingDaysMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ManageWorkingDaysMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ManageWorkingDaysMouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/Manage_Icon.png"))); // NOI18N

        jPanel3.setOpaque(false);
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Manage Room");

        javax.swing.GroupLayout btn_ManageWorkingDaysLayout = new javax.swing.GroupLayout(btn_ManageWorkingDays);
        btn_ManageWorkingDays.setLayout(btn_ManageWorkingDaysLayout);
        btn_ManageWorkingDaysLayout.setHorizontalGroup(
            btn_ManageWorkingDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ManageWorkingDaysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(btn_ManageWorkingDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_ManageWorkingDaysLayout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 214, Short.MAX_VALUE)))
        );
        btn_ManageWorkingDaysLayout.setVerticalGroup(
            btn_ManageWorkingDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ManageWorkingDaysLayout.createSequentialGroup()
                .addGroup(btn_ManageWorkingDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btn_ManageWorkingDaysLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, btn_ManageWorkingDaysLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(btn_ManageWorkingDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_ManageWorkingDaysLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        SidePanel.add(btn_ManageWorkingDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 230, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/ABC Logo 150x150.png"))); // NOI18N
        SidePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 150, 110));

        addWorkingDays_backBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addWorkingDays_backBtn.setForeground(new java.awt.Color(255, 255, 255));
        addWorkingDays_backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/clear btn.png"))); // NOI18N
        addWorkingDays_backBtn.setText("BACK");
        addWorkingDays_backBtn.setToolTipText("Returns Previously Shown Window ");
        addWorkingDays_backBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addWorkingDays_backBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/clear btn hover.png"))); // NOI18N
        addWorkingDays_backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWorkingDays_backBtnActionPerformed(evt);
            }
        });
        SidePanel.add(addWorkingDays_backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 112, 31));

        jPanel6.setBackground(new java.awt.Color(247, 247, 247));
        jPanel6.setPreferredSize(new java.awt.Dimension(625, 329));
        jPanel6.setLayout(new java.awt.CardLayout());

        jp_RoomCannotbeReserved.setBackground(new java.awt.Color(247, 247, 247));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Select Room :");

        rmcnotSelectRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room" }));
        rmcnotSelectRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmcnotSelectRoomActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Select Day :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("Start Time :");

        btn_clearworkingdays.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clearworkingdays.setForeground(new java.awt.Color(255, 255, 255));
        btn_clearworkingdays.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/clear btn.png"))); // NOI18N
        btn_clearworkingdays.setText("CLEAR");
        btn_clearworkingdays.setToolTipText("Click The Clear Button To Clear the data");
        btn_clearworkingdays.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_clearworkingdays.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/clear btn hover.png"))); // NOI18N
        btn_clearworkingdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearworkingdaysActionPerformed(evt);
            }
        });

        addRoomCannotDays.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addRoomCannotDays.setForeground(new java.awt.Color(255, 255, 255));
        addRoomCannotDays.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/add btn.png"))); // NOI18N
        addRoomCannotDays.setText("ADD");
        addRoomCannotDays.setToolTipText("Click The Add Button To Add The Data");
        addRoomCannotDays.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addRoomCannotDays.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/add btn hover.png"))); // NOI18N
        addRoomCannotDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomCannotDaysActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        label1.setText("End Time :");

        rmcannotDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Day", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        javax.swing.GroupLayout jp_RoomCannotbeReservedLayout = new javax.swing.GroupLayout(jp_RoomCannotbeReserved);
        jp_RoomCannotbeReserved.setLayout(jp_RoomCannotbeReservedLayout);
        jp_RoomCannotbeReservedLayout.setHorizontalGroup(
            jp_RoomCannotbeReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_RoomCannotbeReservedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_RoomCannotbeReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_RoomCannotbeReservedLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(addRoomCannotDays, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btn_clearworkingdays, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(194, Short.MAX_VALUE))
                    .addGroup(jp_RoomCannotbeReservedLayout.createSequentialGroup()
                        .addGroup(jp_RoomCannotbeReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rmcnotSelectRoom, 0, 256, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emcntStart_Timetext))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jp_RoomCannotbeReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rmcannotDay, 0, 229, Short.MAX_VALUE)
                            .addComponent(emcntEnd_Timetext))
                        .addGap(47, 47, 47))
                    .addGroup(jp_RoomCannotbeReservedLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(216, 216, 216))))
        );
        jp_RoomCannotbeReservedLayout.setVerticalGroup(
            jp_RoomCannotbeReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_RoomCannotbeReservedLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jp_RoomCannotbeReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_RoomCannotbeReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rmcnotSelectRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rmcannotDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jp_RoomCannotbeReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_RoomCannotbeReservedLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jp_RoomCannotbeReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emcntStart_Timetext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emcntEnd_Timetext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_RoomCannotbeReservedLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)))
                .addGroup(jp_RoomCannotbeReservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRoomCannotDays, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clearworkingdays, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        jPanel6.add(jp_RoomCannotbeReserved, "card2");

        jp_manageRoomCannotbereserved.setBackground(new java.awt.Color(247, 247, 247));

        displayroomcannot_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "         ID", "   Room", "   Day", "Start Time", "End Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        displayroomcannot_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayroomcannot_tableMouseClicked(evt);
            }
        });
        tableScrollPane.setViewportView(displayroomcannot_table);

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/add btn.png"))); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.setToolTipText("Click Update Button To Update Details");
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefresh.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/add btn hover.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/clear btn.png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.setToolTipText("Click Delete Button To Delete Details");
        btndelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndelete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/clear btn hover.png"))); // NOI18N
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/add btn.png"))); // NOI18N
        btnsearch.setText("SEARCH");
        btnsearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsearch.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/add btn hover.png"))); // NOI18N
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search" }));

        javax.swing.GroupLayout jp_manageRoomCannotbereservedLayout = new javax.swing.GroupLayout(jp_manageRoomCannotbereserved);
        jp_manageRoomCannotbereserved.setLayout(jp_manageRoomCannotbereservedLayout);
        jp_manageRoomCannotbereservedLayout.setHorizontalGroup(
            jp_manageRoomCannotbereservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_manageRoomCannotbereservedLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(jp_manageRoomCannotbereservedLayout.createSequentialGroup()
                .addGroup(jp_manageRoomCannotbereservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_manageRoomCannotbereservedLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_manageRoomCannotbereservedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_manageRoomCannotbereservedLayout.setVerticalGroup(
            jp_manageRoomCannotbereservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_manageRoomCannotbereservedLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jp_manageRoomCannotbereservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_manageRoomCannotbereservedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel6.add(jp_manageRoomCannotbereserved, "card3");

        JPanel7.setBackground(new java.awt.Color(20, 181, 117));
        JPanel7.setLayout(new java.awt.CardLayout());

        addWorkingDays_TopBar.setBackground(new java.awt.Color(20, 181, 117));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ROOM CANNOT BE RESERVED");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/clear btn.png"))); // NOI18N
        jButton3.setText("LOGOUT");
        jButton3.setToolTipText("Logout From The System");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/UImages/clear btn hover.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addWorkingDays_TopBarLayout = new javax.swing.GroupLayout(addWorkingDays_TopBar);
        addWorkingDays_TopBar.setLayout(addWorkingDays_TopBarLayout);
        addWorkingDays_TopBarLayout.setHorizontalGroup(
            addWorkingDays_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addWorkingDays_TopBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        addWorkingDays_TopBarLayout.setVerticalGroup(
            addWorkingDays_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addWorkingDays_TopBarLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(addWorkingDays_TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanel7.add(addWorkingDays_TopBar, "card2");

        manageWorkingDays_Topbar.setBackground(new java.awt.Color(20, 181, 117));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MANAGE ROOM");

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn.png"))); // NOI18N
        jButton5.setText("LOGOUT");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn hover.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CANNOT BE RESERVED");

        javax.swing.GroupLayout manageWorkingDays_TopbarLayout = new javax.swing.GroupLayout(manageWorkingDays_Topbar);
        manageWorkingDays_Topbar.setLayout(manageWorkingDays_TopbarLayout);
        manageWorkingDays_TopbarLayout.setHorizontalGroup(
            manageWorkingDays_TopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageWorkingDays_TopbarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(manageWorkingDays_TopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        manageWorkingDays_TopbarLayout.setVerticalGroup(
            manageWorkingDays_TopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageWorkingDays_TopbarLayout.createSequentialGroup()
                .addGroup(manageWorkingDays_TopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageWorkingDays_TopbarLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(manageWorkingDays_TopbarLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        JPanel7.add(manageWorkingDays_Topbar, "card3");

        javax.swing.GroupLayout Background_pnlLayout = new javax.swing.GroupLayout(Background_pnl);
        Background_pnl.setLayout(Background_pnlLayout);
        Background_pnlLayout.setHorizontalGroup(
            Background_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_pnlLayout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(Background_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Background_pnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Background_pnlLayout.setVerticalGroup(
            Background_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Background_pnlLayout.createSequentialGroup()
                .addComponent(JPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addWorkingDaysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addWorkingDaysMouseClicked
        // TODO add your handling code here:
        jp_RoomCannotbeReserved.setVisible(true);
        jp_manageRoomCannotbereserved.setVisible(false);
        addWorkingDays_TopBar.setVisible(true);
        manageWorkingDays_Topbar.setVisible(false);
        btn_addWorkingDays.setBackground(new java.awt.Color(8,142,88));
        btn_ManageWorkingDays.setBackground(new java.awt.Color(39,156,109));
    }//GEN-LAST:event_btn_addWorkingDaysMouseClicked

    private void btn_addWorkingDaysMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addWorkingDaysMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addWorkingDaysMouseEntered

    private void btn_addWorkingDaysMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addWorkingDaysMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addWorkingDaysMouseExited

    private void btn_addWorkingDaysMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addWorkingDaysMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addWorkingDaysMousePressed

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MousePressed

    private void btn_ManageWorkingDaysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ManageWorkingDaysMouseClicked
        // TODO add your handling code here:
        jp_manageRoomCannotbereserved.setVisible(true);
        jp_RoomCannotbeReserved.setVisible(false);
        addWorkingDays_TopBar.setVisible(false);
        manageWorkingDays_Topbar.setVisible(true);
        btn_ManageWorkingDays.setBackground(new java.awt.Color(8,142,88));
        btn_addWorkingDays.setBackground(new java.awt.Color(39,156,109));
    }//GEN-LAST:event_btn_ManageWorkingDaysMouseClicked

    private void btn_ManageWorkingDaysMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ManageWorkingDaysMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ManageWorkingDaysMouseEntered

    private void btn_ManageWorkingDaysMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ManageWorkingDaysMouseExited
        // TODO add your handling code here
    }//GEN-LAST:event_btn_ManageWorkingDaysMouseExited

    private void addWorkingDays_backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWorkingDays_backBtnActionPerformed
        // TODO add your handling code here:
        new ALocationHome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addWorkingDays_backBtnActionPerformed

    private void rmcnotSelectRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmcnotSelectRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmcnotSelectRoomActionPerformed

    private void btn_clearworkingdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearworkingdaysActionPerformed
        // TODO add your handling code here:
       clearFieldsAdd();
    }//GEN-LAST:event_btn_clearworkingdaysActionPerformed

    private void addRoomCannotDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomCannotDaysActionPerformed

        this.roomname = rmcnotSelectRoom.getSelectedItem().toString();
        this.roomday = rmcannotDay.getSelectedItem().toString();
        this.start_time = emcntStart_Timetext.getText();
        this.end_time = emcntEnd_Timetext.getText();

        if (rmcnotSelectRoom.getSelectedItem().toString().equals("Select Room") || rmcannotDay.getSelectedItem().toString().equals("Select Day") || emcntStart_Timetext.getText().equals("") || emcntEnd_Timetext.getText().equals("") ) {
            JOptionPane.showMessageDialog(null, "Please Fill All Fields.");

        } else {
            if ("" != rmcnotSelectRoom.getSelectedItem().toString()) {

                try {
                    String query_roomexits = "select room_name from rmcnnot where room_name like '"+'%'+rmcnotSelectRoom.getSelectedItem().toString()+'%'+"'";
                    Statement st_rooms = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

                    ResultSet rs1 = st_rooms.executeQuery(query_roomexits);
                    if (rs1.first()) {
                        JOptionPane.showMessageDialog(null, "This Room Already Exist");

                    } else {

                        try {
                            String query = "insert into rmcnnot(room_name, day, start_time, end_time) "
                            + "values ( ?, ?, ?, ? )";

                            preparedStmt = connection.prepareStatement(query);
                            preparedStmt.setString(1, roomname);
                            preparedStmt.setString(2, roomday);
                            preparedStmt.setString(3, start_time);
                            preparedStmt.setString(4, end_time);

                            preparedStmt.execute();

                            JOptionPane.showMessageDialog(null, "Cannot Received Room Added Successfully. \n Thank You!");
                            DefaultTableModel model = (DefaultTableModel) displayroomcannot_table.getModel();
                            model.setRowCount(0);
                            show_RoomCannotReceiveDetails();

                            //                    buildingNo.setText("");
                            //                    buildingName.setText("");
                            //                    noRooms.setValue("");

                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, "Something went wrong! Please try again.");
                            System.err.println("Got an exception!");
                            System.err.println(e.getMessage());
                            Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, e);
                        }

                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Something went wrong! Please try again.");
                    System.err.println("Got an exception!");
                    System.err.println(e.getMessage());
                    Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, e);
                }

            }
        }        
       
                
    }//GEN-LAST:event_addRoomCannotDaysActionPerformed

    private void displayroomcannot_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayroomcannot_tableMouseClicked

        int i = displayroomcannot_table.getSelectedRow();
        TableModel model = displayroomcannot_table.getModel();

        roomCnNot_rowSelected = model.getValueAt(i,0).toString();
        roomname = model.getValueAt(i,1).toString();
       
    }//GEN-LAST:event_displayroomcannot_tableMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) displayroomcannot_table.getModel();
        model.setRowCount(0);
        show_RoomCannotReceiveDetails(); 
       
        //  String query = "insert into workingdays(workinghours,workingminiutes,noofworkingdays, monday, tuesday, wednesday, thrusday, friday, saterday, sunday) values(?,?,?,?,?,?,?,?,?,?)";
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Are you sure you want to Delete " + roomCnNot_rowSelected + " - "
            + roomname + "Room details ?", "Delete", JOptionPane.YES_NO_OPTION);

        if (opt == 0) {
            try {
                String query = "DELETE FROM rmcnnot WHERE rmcannot_id = ?";
                preparedStmt = connection.prepareStatement(query);
                preparedStmt.setString(1, roomCnNot_rowSelected);

                preparedStmt.execute();

                JOptionPane.showMessageDialog(null, "Room removed successfully from the Database");
                DefaultTableModel model = (DefaultTableModel) displayroomcannot_table.getModel();
                model.setRowCount(0);
                show_RoomCannotReceiveDetails();

            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Something went wrong! Please try again.");
                System.err.println("Exception in delete operation : " + ex);
                System.err.println(ex.getMessage());
                Logger.getLogger(AAddBuildings.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:

     
    }//GEN-LAST:event_btnsearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UNotAvailableTimeAllocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UNotAvailableTimeAllocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UNotAvailableTimeAllocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UNotAvailableTimeAllocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new URoomCannotBeReserved().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background_pnl;
    private javax.swing.JPanel JPanel7;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JButton addRoomCannotDays;
    private javax.swing.JPanel addWorkingDays_TopBar;
    private javax.swing.JButton addWorkingDays_backBtn;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel btn_ManageWorkingDays;
    private javax.swing.JPanel btn_addWorkingDays;
    private javax.swing.JButton btn_clearworkingdays;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsearch;
    private javax.swing.JTable displayroomcannot_table;
    private javax.swing.JTextField emcntEnd_Timetext;
    private javax.swing.JTextField emcntStart_Timetext;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jp_RoomCannotbeReserved;
    private javax.swing.JPanel jp_manageRoomCannotbereserved;
    private java.awt.Label label1;
    private javax.swing.JPanel manageWorkingDays_Topbar;
    private javax.swing.JComboBox<String> rmcannotDay;
    private javax.swing.JComboBox<String> rmcnotSelectRoom;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
