/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagementsystem;
  
import java.awt.Button;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus
 */
public class VManageSubjects extends javax.swing.JFrame {
    PreparedStatement insert;
    Connection conn;
    /**
     * Creates new form VManageSubjects
     */
    public VManageSubjects() {
        initComponents();
        table_update();
        txtSubCodem.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        HomeBackground_pnl = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        iconlabel = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablesub = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSubCodem = new javax.swing.JTextField();
        txtSubname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        coffyear = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        coffsem = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        spinlec = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        spine = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        spintute = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        spinlab = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HomeBackground_pnl.setBackground(new java.awt.Color(255, 255, 255));
        HomeBackground_pnl.setToolTipText("");
        HomeBackground_pnl.setInheritsPopupMenu(true);
        HomeBackground_pnl.setMaximumSize(new java.awt.Dimension(981, 845));

        jPanel1.setBackground(new java.awt.Color(39, 156, 109));

        jButton12.setBackground(new java.awt.Color(186, 38, 43));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        iconlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vimages/icon.png"))); // NOI18N

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vimages/add_btn_icon.png"))); // NOI18N
        jButton5.setText("Add Subjects");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vimages/add_btn_hover.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vimages/manage_btn_icon.png"))); // NOI18N
        jButton9.setText("         Manage Subjects");
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vimages/manage_btn_hover.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(iconlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jButton12)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(iconlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton12)
                .addContainerGap(582, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(20, 181, 117));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE SUBJECTS");

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn.png"))); // NOI18N
        jButton6.setText("LOGOUT");
        jButton6.setToolTipText("Logout from the system");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/AImages/clear btn hover.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addContainerGap(720, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jTablesub.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Subject Code", "Subject Name", "Offered Year", "Offered Semester", "Lecturer Hours", "Tute Hours", "Lab Hours ", "Evaluation Hours"
            }
        ));
        jTablesub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablesubMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablesub);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 1", "Year 2", "Year 3", "Year 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester 1", "Semester 2" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setText("Select  Semester");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setText("Select Year");

        jButton8.setBackground(new java.awt.Color(34, 108, 252));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Search");
        jButton8.setToolTipText("Click on to search subjects");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("Subject Name:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Subject Code:");

        txtSubCodem.setToolTipText("");
        txtSubCodem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubCodemActionPerformed(evt);
            }
        });

        txtSubname.setToolTipText("Enter Subject Name");
        txtSubname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubnameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Offered Semester:");

        coffyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 1", "Year 2", "Year 3", "Year 4" }));
        coffyear.setToolTipText("Select Subject's offered Year");
        coffyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffyearActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Offered Year:");

        coffsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester 1", "Semester 2" }));
        coffsem.setToolTipText("Select Subject's offered Semester");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setText("Number Of Tutorial Hours:");

        spinlec.setToolTipText("Select Number of lecturer Hours");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setText("Number Of Lecturer Hours:");

        spine.setToolTipText("Select number of  Evaluation Hours");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setText("Number Of Evaluation Hours:");

        spintute.setToolTipText("Select number of  Tutorial Hours");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setText("Number Of Lab Hours:");

        spinlab.setToolTipText("Select number of  Lab Hours");

        jButton4.setBackground(new java.awt.Color(186, 38, 43));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CLEAR");
        jButton4.setToolTipText("Click on to clear values");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(34, 108, 252));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("UPDATE");
        jButton7.setToolTipText("Click on to save changes ");
        jButton7.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jButton7AncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton7MouseMoved(evt);
            }
        });
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(186, 38, 43));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("DELETE");
        jButton11.setToolTipText("Click on to remove subject");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomeBackground_pnlLayout = new javax.swing.GroupLayout(HomeBackground_pnl);
        HomeBackground_pnl.setLayout(HomeBackground_pnlLayout);
        HomeBackground_pnlLayout.setHorizontalGroup(
            HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeBackground_pnlLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HomeBackground_pnlLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(169, Short.MAX_VALUE))
                    .addGroup(HomeBackground_pnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HomeBackground_pnlLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomeBackground_pnlLayout.createSequentialGroup()
                                .addComponent(coffsem, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinlec, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spintute, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinlab, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spine, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(149, 149, 149))
                            .addGroup(HomeBackground_pnlLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(HomeBackground_pnlLayout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(HomeBackground_pnlLayout.createSequentialGroup()
                                .addGroup(HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubCodem, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubname, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coffyear, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        HomeBackground_pnlLayout.setVerticalGroup(
            HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeBackground_pnlLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubCodem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinlec, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spintute, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coffyear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinlab, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spine, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coffsem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(HomeBackground_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(HomeBackground_pnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1318, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     private void table_update(){
    int c;
    
        try {
            
            String currentDir = System.getProperty("user.dir");
             Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            String URL = "jdbc:derby:"+currentDir+"\\TTMS";
            Connection conn = DriverManager.getConnection(URL);
            
            Statement stmt = conn.createStatement();
            
            insert= (PreparedStatement) conn.prepareStatement("select subCode,sname,oyear,osem,nlec,ntute,nlab,nEvaluation from Subject where status = true ");
           
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData res = rs.getMetaData();
            
            c = res.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)jTablesub.getModel();
            df.setRowCount(0);
            
            while (rs.next()){
                
            Vector v2 = new Vector();
            
            for(int a=1; a<=c ; a++){
            
               v2.add(rs.getString("subCode"));
               v2.add(rs.getString("sname"));
               v2.add(rs.getString("oyear"));
               v2.add(rs.getString("osem"));
               v2.add(rs.getString("nlec"));
               v2.add(rs.getString("ntute"));
               v2.add(rs.getString("nlab"));
               v2.add(rs.getString("nEvaluation"));
            }
                  df.addRow(v2);
              }
            
            
       } catch (ClassNotFoundException ex) {
            
            java.util.logging.Logger.getLogger(VManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        } 
        
        catch(SQLException ex){
            java.util.logging.Logger.getLogger(VManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
    
    
    
    
    }
    
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int c;
      
        try{

            String currentDir = System.getProperty("user.dir");
             Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            String URL = "jdbc:derby:"+currentDir+"\\TTMS";
            Connection conn = DriverManager.getConnection(URL);

            Statement stmt = conn.createStatement();

            insert =  (PreparedStatement) conn.prepareStatement("select * from Subject where oyear = ? and osem = ?");
            insert.setString(1, jComboBox1.getSelectedItem().toString());
            insert.setString(2, jComboBox2.getSelectedItem().toString());
            ResultSet rs2 =  insert.executeQuery();

            ResultSetMetaData res = rs2.getMetaData();

            c = res.getColumnCount();

            DefaultTableModel df =(DefaultTableModel) jTablesub.getModel();
            df.setRowCount(0);

            while(rs2.next()){

                Vector v2 = new Vector();

                for(int a=1; a<=c ; a++){

                    v2.add(rs2.getString("subCode"));
                    v2.add(rs2.getString("sname"));
                    v2.add(rs2.getString("oyear"));
                    v2.add(rs2.getString("osem"));
                    v2.add(rs2.getString("nlec"));
                    v2.add(rs2.getString("ntute"));
                    v2.add(rs2.getString("nlab"));
                    v2.add(rs2.getString("nEvaluation"));
                }
                df.addRow(v2);

            }

        }  catch(SQLException ex){
           java.util.logging.Logger.getLogger(VManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }

        catch(ClassNotFoundException ex){
           java.util.logging.Logger.getLogger(VManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtSubCodemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubCodemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubCodemActionPerformed

    private void txtSubnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubnameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       txtSubCodem.setText("");
       txtSubname.setText("");
       coffyear.setSelectedIndex(0);
       coffsem.setSelectedIndex(0);
       spinlec.setValue(0);
       spintute.setValue(0);
       spinlab.setValue(0);
       spine.setValue(0);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        
        
        DefaultTableModel df = (DefaultTableModel) jTablesub.getModel();
        int selectedIndex = jTablesub.getSelectedRow();

        String id = df.getValueAt(selectedIndex,0).toString();

        String sucode = txtSubCodem.getText();
        String suname = txtSubname.getText();
        String offyear = coffyear.getSelectedItem().toString();
        String offsem =coffsem.getSelectedItem().toString();
        String nlec = spinlec.getValue().toString();
        String ntute = spintute.getValue().toString();
        String nlab =spinlab.getValue().toString();
        String eva=spine.getValue().toString();
        
         if ( (!suname.matches("[a-zA-Z_]+"))  ){
             JOptionPane.showMessageDialog(this, "Invalid Subject Name", "Alert", JOptionPane.ERROR_MESSAGE);
}
        
       else if (!sucode.matches("^[A-Z]{2}\\d{4}")){
            JOptionPane.showMessageDialog(this, "Invalid Subject Code", "Alert", JOptionPane.ERROR_MESSAGE);  
       }
                 
       
       else{
        
         try{

            String currentDir = System.getProperty("user.dir");
             Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            String URL = "jdbc:derby:"+currentDir+"\\TTMS";
            Connection conn = DriverManager.getConnection(URL);

            Statement stmt = conn.createStatement();
            
           
            
            //old
            insert = (PreparedStatement) conn.prepareStatement("update Subject set subCode = ?, sname = ?, oyear = ?, osem = ?,nlec =?, ntute = ?, nlab =?, nEvaluation = ? where subCode = ?");
            insert.setString(1,sucode);
            insert.setString(2,suname);
            insert.setString(3,offyear);
            insert.setString(4,offsem);
            insert.setString(5,nlec);
            insert.setString(6,ntute);
            insert.setString(7,nlab);
            insert.setString(8,eva);
                        
             insert.setString(9,id);

            insert.executeUpdate();
            table_update();
            
             JOptionPane.showMessageDialog(this, "Subject is Updated");
             table_update();
             
           
         }
            catch(SQLException ex){
            java.util.logging.Logger.getLogger(VManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }

        catch(ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(VManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
       }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        DefaultTableModel df = (DefaultTableModel)  jTablesub.getModel();
        int selectedIndex =  jTablesub.getSelectedRow();

          String id = df.getValueAt(selectedIndex,0).toString();
        
         try{
             
              int dialogrsult = JOptionPane.showConfirmDialog(null,"Do you want to delete the record ?","warning",JOptionPane.YES_NO_OPTION);

            if(dialogrsult == JOptionPane.YES_OPTION){

            String currentDir = System.getProperty("user.dir");
             Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            String URL = "jdbc:derby:"+currentDir+"\\TTMS";
            Connection conn = DriverManager.getConnection(URL);

            Statement stmt = conn.createStatement();
            
         insert = (PreparedStatement) conn.prepareStatement("update Subject set status =false where subCode = ?");
          insert.setString(1,id);
          
            insert.executeUpdate();
            table_update();
            
             JOptionPane.showMessageDialog(this, "Subject is Deleted");
             
            }
         }
            catch(SQLException ex){
            java.util.logging.Logger.getLogger(VManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }

        catch(ClassNotFoundException ex){
            java.util.logging.Logger.getLogger( VManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void coffyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coffyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coffyearActionPerformed

    private void jTablesubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablesubMouseClicked
        DefaultTableModel df = (DefaultTableModel) jTablesub.getModel();
         int selectedIndex = jTablesub.getSelectedRow();

         txtSubCodem.setText(jTablesub.getValueAt(selectedIndex,0).toString());
         txtSubname.setText(jTablesub.getValueAt(selectedIndex,1).toString());
         coffyear.setSelectedItem(jTablesub.getValueAt(selectedIndex,2).toString());
         coffsem.setSelectedItem(jTablesub.getValueAt(selectedIndex,3).toString());
         spinlec.setValue(Integer.parseInt((String)jTablesub.getValueAt(selectedIndex,4).toString()));
         spintute.setValue(Integer.parseInt((String)jTablesub.getValueAt(selectedIndex,5).toString()));
         spinlab.setValue(Integer.parseInt((String)jTablesub.getValueAt(selectedIndex,6).toString()));
         spine.setValue(Integer.parseInt((String)jTablesub.getValueAt(selectedIndex,7).toString()));
    }//GEN-LAST:event_jTablesubMouseClicked

    private void jButton7AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton7AncestorMoved
      
    }//GEN-LAST:event_jButton7AncestorMoved

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
       
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseMoved
        // JButton b = new JButton( "Accept" );
       // b.setToolTipText( "Click here to accept the option you have selected." );
    }//GEN-LAST:event_jButton7MouseMoved

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        VAddSubjects vr = new VAddSubjects();
        vr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        VManageSubjects vr = new  VManageSubjects();
        vr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
          VsubHome vr = new  VsubHome();
         vr.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VManageSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VManageSubjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomeBackground_pnl;
    private javax.swing.JComboBox<String> coffsem;
    private javax.swing.JComboBox<String> coffyear;
    private javax.swing.JLabel iconlabel;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablesub;
    private javax.swing.JSpinner spine;
    private javax.swing.JSpinner spinlab;
    private javax.swing.JSpinner spinlec;
    private javax.swing.JSpinner spintute;
    private javax.swing.JTextField txtSubCodem;
    private javax.swing.JTextField txtSubname;
    // End of variables declaration//GEN-END:variables
}
